-- Services and prices are intentionally branch-specific. Existing service rows
-- remain for historical booking records, but only rows with branch_id are public.
alter table public.services
  add column if not exists branch_id text references public.branches(id) on delete cascade;

create index if not exists services_branch_price_idx on public.services (branch_id, price);

insert into public.services (id, branch_id, name, description, price, duration_minutes) values
  ('an-dreadlock', 'an-thuong', 'Dreadlock', 'Tạo dreadlock theo độ dài, mật độ và nền tóc; crew tư vấn trước khi làm.', 2000000, 240),
  ('an-single-dread', 'an-thuong', 'Single Dread', 'Làm một dread riêng lẻ, áp dụng cho độ dài 20–30cm.', 150000, 30),
  ('an-pair-dreads', 'an-thuong', 'Pair of Dreads', 'Làm một cặp dread, áp dụng cho độ dài 30–40cm.', 300000, 60),
  ('an-cornrow', 'an-thuong', 'Cornrow 2–8 line', 'Tết cornrow sát da đầu, 150.000đ mỗi line; áp dụng cho 2, 4, 6 hoặc 8 line.', 300000, 90),
  ('an-cornrow-10-16', 'an-thuong', 'Cornrow 10–16 line', 'Tết cornrow sát da đầu, 130.000đ mỗi line; áp dụng cho 10, 12, 14 hoặc 16 line.', 1300000, 180),
  ('an-braids-men', 'an-thuong', 'Braids nam', 'Box braids hoặc pattern theo nền tóc và số section.', 1000000, 180),
  ('an-braids-women', 'an-thuong', 'Braids nữ', 'Box braids theo độ dài, mật độ và thiết kế mong muốn.', 3000000, 300),
  ('an-locs-styling', 'an-thuong', 'Styling locs / braids', 'Thiết kế kiểu locs, twist, cornrow hoặc braids tính theo giờ.', 400000, 60),
  ('an-maintenance-1-worker-first-hour', 'an-thuong', 'Maintenance · 1 thợ · giờ đầu', 'Bảo dưỡng dread/locs với 1 thợ, áp dụng cho giờ đầu tiên.', 400000, 60),
  ('an-maintenance-1-worker-additional-hour', 'an-thuong', 'Maintenance · 1 thợ · giờ tiếp theo', 'Bảo dưỡng dread/locs với 1 thợ, tính từ giờ thứ hai.', 300000, 60),
  ('an-maintenance-2-workers-first-hour', 'an-thuong', 'Maintenance · 2 thợ · giờ đầu', 'Bảo dưỡng dread/locs với 2 thợ, áp dụng cho giờ đầu tiên.', 600000, 60),
  ('an-maintenance-2-workers-second-hour', 'an-thuong', 'Maintenance · 2 thợ · giờ thứ hai', 'Bảo dưỡng dread/locs với 2 thợ, áp dụng cho giờ thứ hai.', 500000, 60),
  ('an-maintenance-2-workers-additional-hour', 'an-thuong', 'Maintenance · 2 thợ · từ giờ thứ ba', 'Bảo dưỡng dread/locs với 2 thợ, tính từ giờ thứ ba trở đi.', 400000, 60),
  ('an-basic-perm', 'an-thuong', 'Uốn basic', 'Uốn cơ bản; giá 300.000–400.000đ tùy độ dài và chất tóc.', 300000, 90),
  ('an-curly-perm', 'an-thuong', 'Uốn xoăn', 'Curly perm; giá 350.000–450.000đ tùy độ dài và chất tóc.', 350000, 120),
  ('an-ruffled-perm', 'an-thuong', 'Uốn Ruffled', 'Ruffled perm; giá 400.000–450.000đ tùy form tóc.', 400000, 120),
  ('an-texture-perm', 'an-thuong', 'Uốn sâu / Texture Perm', 'Uốn sâu tạo texture; giá 400.000–450.000đ tùy chất tóc.', 400000, 120),
  ('an-premlock-perm', 'an-thuong', 'Uốn PremLock', 'PremLock perm; giá 800.000–1.300.000đ tùy độ dài tóc.', 800000, 150),
  ('an-afro-perm', 'an-thuong', 'Uốn Afro', 'Afro perm; giá 1.000.000–1.500.000đ tùy độ dài và mật độ tóc.', 1000000, 180),
  ('an-hair-bleach', 'an-thuong', 'Tẩy tóc', 'Tẩy tóc theo lần tẩy, kiểm tra nền tóc trước khi xử lý.', 250000, 90),
  ('an-root-bleaching', 'an-thuong', 'Tẩy nối chân', 'Tẩy nối chân tóc; giá 400.000–600.000đ theo nền tóc.', 400000, 120),
  ('an-hair-pressed-down', 'an-thuong', 'Ép side', 'Hair pressed down / ép side tóc.', 250000, 60),
  ('an-hair-restore', 'an-thuong', 'Phục hồi tóc', 'Hair restore cho tóc cần phục hồi; giá 300.000–400.000đ.', 300000, 90),
  ('an-beard-dye', 'an-thuong', 'Nhuộm râu', 'Beard dye; giá 150.000–250.000đ theo tình trạng râu.', 150000, 45),
  ('an-black-dye', 'an-thuong', 'Nhuộm đen', 'Black dye; giá 150.000–250.000đ theo nền tóc.', 150000, 60),
  ('an-haircut-styling', 'an-thuong', 'Cắt tóc & tạo kiểu', 'Cắt tóc, tạo kiểu với Uppercut; thời lượng 45 phút.', 150000, 45),
  ('an-hot-cold-towel-shave', 'an-thuong', 'Cạo khăn nóng & lạnh', 'Hot & cold towel shave; thời lượng 30 phút.', 120000, 30),
  ('an-basic-beard-trim-side', 'an-thuong', 'Tỉa râu cơ bản / cắt side', 'Tỉa râu cơ bản hoặc chỉ cắt phần side; thời lượng 25 phút.', 100000, 25),
  ('an-hair-styling', 'an-thuong', 'Sấy & tạo kiểu tóc', 'Hair styling sau khi gội hoặc cắt tóc.', 100000, 30),
  ('an-hair-washing', 'an-thuong', 'Gội đầu thường', 'Hair washing cơ bản.', 50000, 30),
  ('an-locs-washing', 'an-thuong', 'Gội & làm sạch Dreads / Locs', 'Giá 50.000–150.000đ tùy độ dài dread hoặc locs.', 50000, 45),
  ('an-afro-wash-blowdry', 'an-thuong', 'Gội & sấy tóc Afro', 'Afro hair wash & blow-dry; giá 100.000–200.000đ.', 100000, 60),
  ('an-basic-hair-tattoo', 'an-thuong', 'Tattoo tóc cơ bản', 'Basic hair tattoo; giá 50.000–150.000đ theo thiết kế.', 50000, 30),
  ('an-gentlemans-set-1', 'an-thuong', 'Gentleman''s Set I', 'Cắt tóc + cạo khăn nóng/lạnh + Uppercut.', 250000, 75),
  ('an-gentlemans-set-2', 'an-thuong', 'Gentleman''s Set II', 'Cắt tóc + gội + cạo khăn nóng/lạnh + Uppercut.', 290000, 90),
  ('an-vip-gentlemans-combo', 'an-thuong', 'VIP Gentleman''s Combo', 'Chỉ nhận đặt lịch trước; tư vấn tạo kiểu, haircut/shave theo yêu cầu, khăn nóng/lạnh, grooming và quyền ưu tiên.', 390000, 120),
  ('cd-haircut', 'chuong-duong', 'Cắt tóc & tạo kiểu', 'Cắt tóc và tạo kiểu với pomade.', 120000, 45),
  ('cd-sides-back-fade', 'chuong-duong', 'Fade hai bên & gáy', 'Làm gọn phần hai bên và gáy.', 90000, 30),
  ('cd-long-haircut', 'chuong-duong', 'Cắt tóc nam dài', 'Cắt và chỉnh form cho tóc nam dài.', 200000, 60),
  ('cd-wash-blowdry', 'chuong-duong', 'Gội & sấy tạo kiểu', 'Gội, sấy và tạo kiểu với pomade.', 70000, 30),
  ('cd-keratin-therapy', 'chuong-duong', 'Phục hồi Keratin', 'Phục hồi Keratin cho tóc khô xơ; giá 200.000–400.000đ tùy tình trạng tóc.', 200000, 60),
  ('cd-down-perm', 'chuong-duong', 'Ép side tóc', 'Down perm làm gọn side tóc.', 250000, 60),
  ('cd-basic-perm', 'chuong-duong', 'Uốn basic', 'Uốn cơ bản; giá 300.000–400.000đ tùy độ dài và nền tóc.', 300000, 90),
  ('cd-curly-perm', 'chuong-duong', 'Uốn xoăn', 'Curly perm; giá 350.000–450.000đ tùy độ dài và độ xoăn mong muốn.', 350000, 120),
  ('cd-ruffled-perm', 'chuong-duong', 'Uốn Ruffled', 'Ruffled perm; giá 400.000–500.000đ tùy form tóc.', 400000, 120),
  ('cd-premlock-perm', 'chuong-duong', 'Uốn PremLock', 'Uốn PremLock; giá 800.000–1.200.000đ tùy nền tóc.', 800000, 150),
  ('cd-afro-perm', 'chuong-duong', 'Uốn Afro', 'Afro perm; giá 1.000.000–1.500.000đ tùy độ dài và mật độ tóc.', 1000000, 180),
  ('cd-hair-bleaching', 'chuong-duong', 'Tẩy tóc', 'Hair bleaching, tính theo mỗi lần tẩy.', 250000, 90),
  ('cd-bleach-root-touch-up', 'chuong-duong', 'Tẩy nối chân tóc', 'Bleach root touch-up; giá 500.000–900.000đ tùy nền tóc.', 500000, 120),
  ('cd-hair-color', 'chuong-duong', 'Nhuộm tóc thời trang', 'Nhuộm màu thời trang; giá 250.000–350.000đ tùy nền tóc và màu chọn.', 250000, 90),
  ('cd-hair-blackening', 'chuong-duong', 'Nhuộm đen', 'Hair blackening; giá 150.000–250.000đ tùy nền tóc.', 150000, 60),
  ('cd-beard-coloring', 'chuong-duong', 'Nhuộm râu', 'Beard coloring; giá 150.000–250.000đ tùy tình trạng râu.', 150000, 45),
  ('cd-basic-beard-coloring', 'chuong-duong', 'Nhuộm râu cơ bản', 'Basic beard coloring.', 100000, 30),
  ('cd-basic-hair-tattoo', 'chuong-duong', 'Tattoo tóc cơ bản', 'Basic hair tattoo; giá 50.000–150.000đ theo thiết kế.', 50000, 30),
  ('cd-hair-washing', 'chuong-duong', 'Gội đầu thư giãn', 'Hair washing cơ bản.', 40000, 30),
  ('cd-haircut-expert', 'chuong-duong', 'Cắt tóc bởi chuyên gia', 'Chỉ nhận đặt lịch trước.', 160000, 60),
  ('cd-beard-trim', 'chuong-duong', 'Tỉa râu', 'Tạo form và làm gọn râu.', 80000, 30),
  ('cd-basic-beard-trim-line-up', 'chuong-duong', 'Tỉa râu cơ bản / cạo viền', 'Basic beard trim hoặc line-up.', 70000, 25),
  ('cd-full-head-face-shave', 'chuong-duong', 'Cạo đầu / cạo mặt', 'Full head shave hoặc face shave.', 70000, 30),
  ('cd-hot-towel-shave', 'chuong-duong', 'Cạo khăn nóng & lạnh', 'Cạo mặt với khăn nóng và lạnh.', 60000, 30)
on conflict (id) do update set
  branch_id = excluded.branch_id,
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  duration_minutes = excluded.duration_minutes;

delete from public.barber_services
where barber_id in ('kai-loc', 'linh-color', 'son-line', 'minh-fade', 'ryo-beard', 'bao-crop', 'hieu-wave');

insert into public.barber_services (barber_id, service_id) values
  ('kai-loc', 'an-dreadlock'), ('kai-loc', 'an-single-dread'), ('kai-loc', 'an-pair-dreads'), ('kai-loc', 'an-cornrow'), ('kai-loc', 'an-cornrow-10-16'),
  ('kai-loc', 'an-braids-men'), ('kai-loc', 'an-braids-women'), ('kai-loc', 'an-locs-styling'), ('kai-loc', 'an-locs-washing'),
  ('kai-loc', 'an-maintenance-1-worker-first-hour'), ('kai-loc', 'an-maintenance-1-worker-additional-hour'),
  ('kai-loc', 'an-maintenance-2-workers-first-hour'), ('kai-loc', 'an-maintenance-2-workers-second-hour'), ('kai-loc', 'an-maintenance-2-workers-additional-hour'),
  ('linh-color', 'an-basic-perm'), ('linh-color', 'an-curly-perm'), ('linh-color', 'an-ruffled-perm'), ('linh-color', 'an-texture-perm'), ('linh-color', 'an-premlock-perm'), ('linh-color', 'an-afro-perm'),
  ('linh-color', 'an-hair-bleach'), ('linh-color', 'an-root-bleaching'), ('linh-color', 'an-hair-pressed-down'), ('linh-color', 'an-hair-restore'), ('linh-color', 'an-black-dye'),
  ('linh-color', 'an-locs-styling'), ('linh-color', 'an-braids-men'), ('linh-color', 'an-braids-women'),
  ('son-line', 'an-haircut-styling'), ('son-line', 'an-hot-cold-towel-shave'), ('son-line', 'an-basic-beard-trim-side'), ('son-line', 'an-hair-styling'),
  ('son-line', 'an-hair-washing'), ('son-line', 'an-afro-wash-blowdry'), ('son-line', 'an-basic-hair-tattoo'), ('son-line', 'an-beard-dye'),
  ('son-line', 'an-gentlemans-set-1'), ('son-line', 'an-gentlemans-set-2'), ('son-line', 'an-vip-gentlemans-combo'),
  ('son-line', 'an-locs-styling'), ('son-line', 'an-cornrow'), ('son-line', 'an-single-dread'),
  ('son-line', 'an-maintenance-2-workers-first-hour'), ('son-line', 'an-maintenance-2-workers-second-hour'), ('son-line', 'an-maintenance-2-workers-additional-hour'),
  ('minh-fade', 'cd-haircut'), ('minh-fade', 'cd-sides-back-fade'), ('minh-fade', 'cd-long-haircut'), ('minh-fade', 'cd-wash-blowdry'),
  ('minh-fade', 'cd-basic-hair-tattoo'), ('minh-fade', 'cd-hair-washing'), ('minh-fade', 'cd-haircut-expert'),
  ('ryo-beard', 'cd-haircut'), ('ryo-beard', 'cd-beard-trim'), ('ryo-beard', 'cd-basic-beard-trim-line-up'), ('ryo-beard', 'cd-full-head-face-shave'), ('ryo-beard', 'cd-hot-towel-shave'),
  ('ryo-beard', 'cd-beard-coloring'), ('ryo-beard', 'cd-basic-beard-coloring'),
  ('bao-crop', 'cd-haircut'), ('bao-crop', 'cd-sides-back-fade'), ('bao-crop', 'cd-long-haircut'), ('bao-crop', 'cd-wash-blowdry'),
  ('bao-crop', 'cd-basic-hair-tattoo'), ('bao-crop', 'cd-hair-washing'), ('bao-crop', 'cd-haircut-expert'), ('bao-crop', 'cd-down-perm'), ('bao-crop', 'cd-basic-perm'),
  ('hieu-wave', 'cd-keratin-therapy'), ('hieu-wave', 'cd-down-perm'), ('hieu-wave', 'cd-basic-perm'), ('hieu-wave', 'cd-curly-perm'), ('hieu-wave', 'cd-ruffled-perm'),
  ('hieu-wave', 'cd-premlock-perm'), ('hieu-wave', 'cd-afro-perm'), ('hieu-wave', 'cd-hair-bleaching'), ('hieu-wave', 'cd-bleach-root-touch-up'),
  ('hieu-wave', 'cd-hair-color'), ('hieu-wave', 'cd-hair-blackening');
