create table if not exists public.messenger_events (
  message_id text primary key,
  sender_id text not null,
  received_at timestamptz not null default now()
);

create table if not exists public.messenger_messages (
  id bigint generated by default as identity primary key,
  sender_id text not null,
  role text not null check (role in ('user', 'model')),
  content text not null check (char_length(content) between 1 and 4000),
  created_at timestamptz not null default now()
);

create index if not exists messenger_messages_sender_created_idx
  on public.messenger_messages (sender_id, created_at desc);

create index if not exists messenger_events_received_idx
  on public.messenger_events (received_at);

alter table public.messenger_events enable row level security;
alter table public.messenger_messages enable row level security;

revoke all on table public.messenger_events from anon, authenticated;
revoke all on table public.messenger_messages from anon, authenticated;
revoke all on sequence public.messenger_messages_id_seq from anon, authenticated;

grant select, insert, delete on table public.messenger_events to service_role;
grant select, insert, delete on table public.messenger_messages to service_role;
grant usage, select on sequence public.messenger_messages_id_seq to service_role;

comment on table public.messenger_events is
  'Processed Meta Messenger message IDs, used to make webhook retries idempotent.';

comment on table public.messenger_messages is
  'Short Messenger conversation history used by the WINDREAD Vertex AI assistant.';
