"use client";

import { useEffect, useState } from "react";
import { adminFetch, downloadCsv, formatDateTime, formatVnd } from "../admin-ui";
import { AdminFrame, useAdminSession } from "../components/AdminFrame";

type Invoice = { id: string; invoice_number: string; status: "draft" | "completed" | "voided" | "refunded"; total_amount: number; discount_amount: number; completed_at: string | null; created_at: string; note: string | null; customers: { name: string; phone: string } | null; payments: Array<{ method: string; direction: string; amount: number }> | null };

function Invoices() {
  const { branchId, user } = useAdminSession();
  const [invoices, setInvoices] = useState<Invoice[]>([]); const [message, setMessage] = useState(""); const [refundId, setRefundId] = useState(""); const [reason, setReason] = useState("");
  const load = () => adminFetch<{ invoices: Invoice[] }>(`/api/admin/invoices?branchId=${encodeURIComponent(branchId)}`).then((data) => setInvoices(data.invoices)).catch((error: unknown) => setMessage(error instanceof Error ? error.message : "Không tải được hóa đơn."));
  useEffect(() => { load(); }, [branchId]);
  async function refund(invoice: Invoice) { try { await adminFetch("/api/admin/invoices", { method: "PATCH", body: JSON.stringify({ invoiceId: invoice.id, reason }) }); setMessage(`Đã hoàn tiền ${invoice.invoice_number} và tạo các bút toán đảo.`); setRefundId(""); setReason(""); load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Không thể hoàn tiền."); } }
  function exportCsv() { downloadCsv(`hoa-don-${branchId}.csv`, ["Mã hóa đơn", "Khách hàng", "Điện thoại", "Thời gian", "Thanh toán", "Giảm giá", "Tổng tiền", "Trạng thái"], invoices.map((invoice) => [invoice.invoice_number, invoice.customers?.name || "Khách vãng lai", invoice.customers?.phone, invoice.completed_at || invoice.created_at, invoice.payments?.filter((payment) => payment.direction === "in").map((payment) => payment.method).join(" + "), invoice.discount_amount, invoice.total_amount, invoice.status])); }
  return <section className="admin-panel"><header><div><p className="admin-kicker">Lịch sử giao dịch</p><h2>Hóa đơn & hoàn tiền</h2></div><button className="admin-text-button" onClick={exportCsv} disabled={!invoices.length}>Xuất CSV</button></header>{message && <p className={message.startsWith("Đã") ? "admin-form-success" : "admin-form-error"}>{message}</p>}<div className="admin-table-wrap"><table><thead><tr><th>Mã hóa đơn</th><th>Khách hàng</th><th>Thời gian</th><th>Thanh toán</th><th>Tổng tiền</th><th>Trạng thái</th><th /></tr></thead><tbody>{invoices.map((invoice) => <><tr key={invoice.id}><td><strong>{invoice.invoice_number}</strong><small>{invoice.note || "—"}</small></td><td>{invoice.customers?.name || "Khách vãng lai"}<small>{invoice.customers?.phone || "—"}</small></td><td>{formatDateTime(invoice.completed_at || invoice.created_at)}</td><td>{invoice.payments?.filter((payment) => payment.direction === "in").map((payment) => payment.method === "cash" ? "Tiền mặt" : payment.method).join(", ") || "—"}</td><td><strong>{formatVnd(invoice.total_amount)}</strong><small>Giảm {formatVnd(invoice.discount_amount)}</small></td><td><span className={`admin-status ${invoice.status === "completed" ? "is-open" : "is-closed"}`}>{invoice.status === "completed" ? "Hoàn tất" : invoice.status === "refunded" ? "Đã hoàn" : invoice.status}</span></td><td>{invoice.status === "completed" && (user.role === "admin" || user.role === "manager") && <button className="admin-text-button danger" onClick={() => setRefundId(refundId === invoice.id ? "" : invoice.id)}>Hoàn tiền</button>}</td></tr>{refundId === invoice.id && <tr key={`${invoice.id}-refund`}><td colSpan={7}><div className="admin-inline-refund"><label>Lý do hoàn tiền<input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Nhập lý do bắt buộc" /></label><button className="admin-button" disabled={!reason.trim()} onClick={() => refund(invoice)}>Xác nhận hoàn tiền</button><button className="admin-text-button" onClick={() => { setRefundId(""); setReason(""); }}>Hủy</button></div></td></tr>}</>)}</tbody></table>{!invoices.length && <p className="admin-empty">Chưa có hóa đơn tại chi nhánh này.</p>}</div></section>;
}

export default function InvoicesPage() { return <AdminFrame title="Hóa đơn" eyebrow="Tra cứu, in phiếu và hoàn tiền có kiểm soát"><Invoices /></AdminFrame>; }
